{% set name = "multiprocess" %}
{% set version = "0.70.18" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9597128e6b3e67b23956da07cf3d2e5cba79e2f4e0fba8d7903636663ec6d0d

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=42
    - dill
  run:
    - python
    - dill >=0.4.0

test:
  imports:
    - multiprocess
    - multiprocess.dummy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uqfoundation/multiprocess
  summary: better multiprocessing and multithreading in python
  description: |
    `multiprocess` is a fork of `multiprocessing`. `multiprocess` extends `multiprocessing` to provide enhanced serialization, using `dill`. `multiprocess` leverages `multiprocessing` to support the spawning of processes using the API of the python standard library's `threading module. multiprocessing has been distributed as part of the standard library since python 2.6.
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - COPYING
    - LICENSE
  doc_url: https://multiprocess.readthedocs.io
  dev_url: https://github.com/uqfoundation/multiprocess

extra:
  recipe-maintainers:
    - jschueller
