{% set name = "multiprocess" %}
{% set version = "0.70.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46479a327388df8e77ad268892f2e73eac06d6271189b868ce9d4f95474e58e3

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=0.6
    - dill >=0.2.5
  run:
    - python
    - dill >=0.2.5

test:
  imports:
    - _multiprocess
    - multiprocess
    - multiprocess.dummy

about:
  home: http://trac.mystic.cacr.caltech.edu/project/pathos/wiki.html
  license: BSD-3-Clause
  license_file: COPYING.txt
  summary: better multiprocessing and multithreading in python

extra:
  recipe-maintainers:
    - jschueller
