{% set name = "multiprocess" %}
{% set version = "0.70.14" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3eddafc12f2260d27ae03fe6069b12570ab4764ab59a75e81624fac453fbf46a

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    - dill
  run:
    - python
    - dill >=0.3.6

test:
  imports:
    - multiprocess
    - multiprocess.dummy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uqfoundation/multiprocess
  summary: better multiprocessing and multithreading in python
  license: BSD-3-Clause
  license_file:
    - COPYING
    - LICENSE
extra:
  recipe-maintainers:
    - jschueller
