{% set name = "multiprocess" %}
{% set version = "0.70.14" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3eddafc12f2260d27ae03fe6069b12570ab4764ab59a75e81624fac453fbf46a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools >=0.6
    - dill >=0.2.5
  run:
    - python
    - dill >=0.2.5

test:
  imports:
    - multiprocess
    - multiprocess.dummy

about:
  home: https://pypi.org/project/multiprocess/
  license: BSD-3-Clause
  license_file: COPYING.txt
  summary: better multiprocessing and multithreading in python

extra:
  recipe-maintainers:
    - jschueller
