travis:
  secure:
    BINSTAR_TOKEN: qcHe+bo0KzOF/c/sSgxND2rFh2Z7gMQFA4lda+8vFeQ5qcMx3k5qypxBODPoQBaivddDf/xYy5In7XWyhac6hSRBEQZ0rGFs2FGp5mUDJOrRE3sIv3v5rg+C16tQhnCHsNiN5KQzIonXVbSgzuhMJHNXuLmiJhOaKJR/HsX3dl5hqoHFKB6N+b3LP1e0Osnag/aizeOMFMs3R0ThAdECM/UTSViFHEAsBT5wHuxV4dWg9nB5eyyzwegpjEiqFUzSjPUELDYxFLybw01cR3e7107t52pJROdSTBNsuUAVgkiC34DsCWt3wRUF4ohyiYDnzo33yMU0J8NeANYpikUIRXlMId04WdK8Kj69vGO0l1L6YPn7w11R7rihWZpSU4jnV5TPJzFgfYRHcYJruDTZsWgkent4CoL4ph47tHuVqpQf2yUiwjiIjpKU/caZ6YiYMTyEcqAhoTWIkeN7/uHmNflqjtm7tHEO7kWM376uukxxoA1wKFEZ4M4PlYG65NlTJCUxYtocFfsAuSd1wtG3Bjzy0BvjUNgYdX9UyW5/UER2pzhndtYtFUdTQN1JHAN6/+7SQYcvyND6RJvpfsCC8l5hVbJJVOU/4r3FdLjbqUm4qSKhwZ4+5pIQxz8KSo1wO133LdOA+IAgOIQ9Dy32rhZe/yRCwcaI4sJApHvUZ+A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
